name: Convert PieceCID v1 to v2 with log2 size

on:
  workflow_dispatch:
    inputs:
      piece:
        required: true
        description: PieceCID of to convert
        type: string
      log2:
        required: true
        description: Log2 Size of the Piece
        type: number

jobs:
  convertPieceCidV1ToV2WithLog2Size:
    name: Convert PieceCID v1 to v2 with log2 size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Run job
        run: npm run convert-piece-cid-v1-to-v2-with-log2-size -w packages/tools ${{ github.event.inputs.piece }} ${{ github.event.inputs.log2 }}
