name: Convert PieceCID v1 to v2 with height

on:
  workflow_dispatch:
    inputs:
      piece:
        required: true
        description: PieceCID of to convert
        type: string
      height:
        required: true
        description: Height of the Piece
        type: number

jobs:
  convertPieceCidV1ToV2WithHeight:
    name: Convert PieceCID v1 to v2 with height
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 18
          cache: 'npm'
      - run: npm install @web3-storage/pieces
      - name: Run job
        run: npx @web3-storage/pieces v2 ${{ github.event.inputs.piece }} --height ${{ github.event.inputs.height }}
